version: "3"

services:
  app:
    image: node:13.12-alpine
    ports:
      - 3000:3000
    expose:
      - 3000
    command: npm run start:debug
    volumes:
      - .:/usr/src/app
      - public_nodemodules:/usr/app/node_modules
    working_dir: /usr/src/app/

volumes:
  public_nodemodules:
    external: true
