version: "3"

services:
  db:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - "./scripts/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh"
      - "/docker/tmp/postgres/data:/var/lib/postgres/data"
  redis:
    image: redis:6.0-rc-alpine
    ports:
      - "6380:6380"
    expose:
      - "6380"
    volumes:
      - "/docker/tmp/redis/data:/var/lib/redis/data"
      - "./redis.dev.conf:/usr/local/etc/redis/redis.conf"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]