version: "3"

services:
  db:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - "./scripts/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh"
  session_store:
    image: redis:6.0-rc1
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - "/docker/tmp/redis/data:/var/lib/redis/data"