version: "3.7"

services:
  db:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_USER: universities
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: